#!/bin/sh
CONF_FILE=/etc/lighttpd/lighttpd.conf

grep -q 'luci' ${CONF_FILE} 2>/dev/null
[ $? -eq 1 ] && {
	sed -i \
		-e 's!#\(server.modules = (\)!\1!' \
		-e 's!#\(\t"mod_redirect",\)!\1!' \
		-e 's!#\(\t"mod_cgi"\),!\1!' \
		-e '/#\t"mod_webdav"/{ N; s!\(#\t"mod_webdav"\n\)#!\1! }' \
		$CONF_FILE

	echo -e >>${CONF_FILE}
	echo -e >>${CONF_FILE} '$HTTP["url"] =~ "^/cgi-bin/" {'
	echo -e >>${CONF_FILE} '\tcgi.assign = ( "luci"  => "/usr/bin/lua" )'
	echo -e >>${CONF_FILE} '}'
	echo -e >>${CONF_FILE}
	echo -e >>${CONF_FILE} 'url.redirect = ('
	echo -e >>${CONF_FILE} '\t"^/($|index.html$)"\t=> "/cgi-bin/luci",'
	echo -e >>${CONF_FILE} '\t"^/luci$"\t\t=> "/cgi-bin/luci"'
	echo -e >>${CONF_FILE} ')'
}
