#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org
START=95
USE_PROCD=1

reload_service() {
	restart_service
}

service_triggers()
{
	procd_add_reload_trigger "cheapl"
}

start_service() {
	config_load cheapl
#	config_get name        $1 name        "${hostname:-OpenWrt}"
#	config_get workgroup   $1 workgroup   "${hostname:-OpenWrt}"
#	network_get_ipaddr  ip "lan"

	procd_open_instance
	procd_set_param command /usr/bin/cheapl
	procd_set_param respawn
	procd_close_instance
}
