#
# Copyright (C) 2009-2011 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=attr
PKG_VERSION:=2.4.46
PKG_RELEASE:=1

PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).src.tar.gz
PKG_SOURCE_URL:=http://download.savannah.gnu.org/releases/attr/

include $(INCLUDE_DIR)/package.mk

EXTRA_LDFLAGS += -Wl,-rpath-link=$(STAGING_DIR)/usr/lib

define Package/libattr
  SECTION:=libs
  CATEGORY:=Libraries
  TITLE:=Library for Manipulating Filesystem Extended Attributes
  URL:=http://download.savannah.gnu.org
endef

define Package/libattr/description
 Library for Manipulating Filesystem Extended Attributes
endef

define Package/attr
  SECTION:=utilities
  CATEGORY:=Utilities
  TITLE:=Commands for Manipulating Filesystem Extended Attributes
  URL:=http://download.savannah.gnu.org
  DEPENDS:= +libattr
endef

define Package/attr/description
 Commands for Manipulating Filesystem Extended Attributes
endef

define Build/Compile
	$(MAKE) -C $(PKG_BUILD_DIR) \
		DESTDIR="$(PKG_INSTALL_DIR)-dev" \
		PKG_BIN_DIR="$(PKG_INSTALL_DIR)-dev/usr/bin" \
		MAN_DEST="$(PKG_INSTALL_DIR)-dev/usr/man" \
		PKG_DOC_DIR="$(PKG_INSTALL_DIR)-dev/usr/share/doc/attr" \
		PKG_LOCALE_DIR="$(PKG_INSTALL_DIR)-dev/usr/share/locale" \
		PKG_INC_DIR="$(PKG_INSTALL_DIR)-dev/usr/include" \
		PKG_LIB_DIR="$(PKG_INSTALL_DIR)-dev/usr/lib" \
		PKG_DEVLIB_DIR="$(PKG_INSTALL_DIR)-dev/usr/lib" \
		install-dev
endef

define Package/libattr/install
	$(INSTALL_DIR) $(1)/usr/lib
	$(CP) $(PKG_INSTALL_DIR)/usr/lib/libattr.so* $(1)/usr/lib
endef

define Package/attr/install
	$(INSTALL_DIR) $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/attr $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/getfattr $(1)/usr/bin
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/setfattr $(1)/usr/bin
endef

define Build/InstallDev
	$(INSTALL_DIR) $(1)/usr/include/attr
	$(CP) $(PKG_INSTALL_DIR)/usr/include/* $(1)/usr/include
	$(INSTALL_DIR) $(1)/usr/lib
	$(CP) $(PKG_INSTALL_DIR)/usr/lib/libattr.{a,so*} $(1)/usr/lib
endef

$(eval $(call BuildPackage,attr))
$(eval $(call BuildPackage,libattr))
